services:
  grimoire:
    build:
      context: .
      dockerfile: Dockerfile
      target: project
    container_name: grimoire
    environment:
      - MAIN_API_URL=http://127.0.0.1:5001
      - MAIN_API_AUTH=AuthKey
      - SIDE_API_URL=http://127.0.0.1:5002
      - CONTEXT_PERCENTAGE=0.25
      - DB_ENGINE=sqlite:///db.sqlite3
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG = True
      - LOG_PROMPTS = True
    ports:
      - 5005:5005

  redis:
    image: redis
    container_name: 'redis'
    ports:
      - 6379:6379