services:
  grimoire:
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    container_name: grimoire
    env_file: .env_template
    ports:
      - 5005:5005

  redis:
    image: redis
    container_name: 'redis'
    ports:
      - 6379:6379
