services:
  redis:
    image: redis
    container_name: "redis"
    ports:
      - 6379:6379

  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_USER=grimoire
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=grimoire
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
