DEBUG: True
LOG_PROMPTS: True
single_api_mode: False
context_percentage: 0.25
main_api:
  backend: GenericOAI
  url: !env MAIN_API_URL
  auth_key: !env MAIN_API_AUTH
side_api:
  backend: GenericOAI
  url: !env SIDE_API_URL
  auth_key: !env SIDE_API_AUTH
  input_sequence: '### Instruction:\n'
  output_sequence: '\n### Response:\n'
