name: Build

on: push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - 
        name: Build project
        uses: docker/build-push-action@v5
        with:
          push: false
          target: project
